### ISSUE TITLE
handle_message method should return reasoning outputs

### ISSUE THREAD

**Issue by roquelopez** [VIDA-NYU/tim-reasoning#16]
The [handle_message](https://github.com/VIDA-NYU/tim-reasoning/blob/ee855b135ad1a2f8519209482d7dd5528a6d522b/tim_reasoning/manager/session_manager.py#L260) method should return the outputs from reasoning, e.g. current_step, error status. So far they are printed on the logs, but we need the actual objects to send them to the other modules.

**Comment by sakshambassi** [comment]
{
`session_id` is task_manager's id
`task_id` is name of recipe
`step_id` is the current step (not finished)
`step_status` is always "IN_PROGRESS"
`step_description` is the current step's instruction
`error_status` is boolean i.e. whether in the current step an error was found or not.
`error_description` is type of error and explanation of error.
}
